### ISSUE TITLE
Error in  README.md

### ISSUE THREAD

**Issue by retroryan** [Marcinthecloud/Solr-Amazon-Book-Demo#1]
In the README.md it says:

"for package installs: set SOLR=1 in the dse.default file and run: service dse start"

The correct way is:

"for package installs: set SOLR_ENABLED=1 in /etc/default/dse file and run: service dse start"

see the following docs for details:
[http://docs.datastax.com/en/datastax_enterprise/5.0/datastax_enterprise/admin/startDseService.html](http://docs.datastax.com/en/datastax_enterprise/5.0/datastax_enterprise/admin/startDseService.html)

**Comment by Marcinthecloud** [comment]
Fixed and committed. Thanks Ryan!
